### ISSUE TITLE
Offline version?

### ISSUE THREAD

**Issue by Tg10110** [DarthWound/papirus-kolorizer#1]
Would it be possible to point the script to a local copy of papyrus, so that it doesn't have to redownload it every time? I'm trying to sync everything up to wal, if you're wondering why.

**Comment by DarthWound** [comment]
Aw, yeah, Papirus installer grab the files online too, sorry.

So in my script at [line74](https://github.com/DarthWound/papirus-kolorizer/blob/master/papirus-kolorizer.sh#L74) instead of `./install.sh` put this, it should be enough:

System-wide installation *(recommended)*:
```
rm -rf $HOME/.icons/*Papirus* $HOME/.local/share/icons/*Papirus*
sudo rm -rf /usr/share/icons/*Papirus*
sleep 2s # I put a sleep here to be sure that old files are removed before copying new files
sudo cp -r Papirus Papirus-Light Papirus-Dark /usr/share/icons
sudo gtk-update-icon-cache
```

User installation:
```
rm -rf $HOME/.icons/*Papirus* $HOME/.local/share/icons/*Papirus*
sudo rm -rf /usr/share/icons/*Papirus*
sleep 2s # I put a sleep here to be sure that old files are removed before copying new files
cp -r Papirus Papirus-Light Papirus-Dark $HOME/.icons/
gtk-update-icon-cache
```

Didn't try yet because I'm too busy, but it should work, tell me if it's ok :)

**Comment by Tg10110** [comment]
oof. Script executes, but i'm getting no icons. No papirus icons in lxappearance, either.

**Comment by DarthWound** [comment]
Weird, I tried after seeing your comment and it works.

You don't see Papirus in `/usr/share/icons/`?

Are you following the 3 steps [here](https://github.com/DarthWound/papirus-kolorizer/issues/1#issuecomment-376544221)?

Does installing Papirus from "online" script work for you? Your user account has sudo permissions?

Send a gist or a screenshot of your modified script.

**Comment by Tg10110** [comment]
I do indeed see papirus in `/usr/share/icons`.

I did follow the three steps. As you can see from my first screenshot, the files are as ordered.

The online script works perfectly. Though still not automated....

gist here https://gist.github.com/Tg10110/ea2bf3a39939ddf499acabfbbd6800f3

**Comment by DarthWound** [comment]
Maybe some caching issue with lxappearance or your wm?

Did you try restarting your session?

**Comment by Tg10110** [comment]
tried restarting. no luck. i'm using i3.

**Comment by DarthWound** [comment]
Yeah I recognized i3 *(-gaps, I guess)*. Did you try using another de/wm *(just for testing)*?

I really don't know what's the problem here.
