### ISSUE TITLE
Est-ce que MIT est compatible avec GPL3 ?

### ISSUE THREAD

**Issue by gusbemacbe** [DarthWound/papirus-kolorizer#2]
Salut @DarthWound !

Je voudrais faire _fork_ de votre répositoire pour mon thème d'icônes Suru++ et changer tout, mais maintenir votre crédit, parce que quelqu’un peut changer rapidement les couleurs sans dépendre d'Oomox. Je veux savoir se je peux accorder une sous-licence au répositoire pour GPL3. 

Merci pour votre attention !

**Comment by DarthWound** [comment]
Hi, FYI you can speak english.

MIT license explicitly allows sublicensing, so no problem. IIRC original code must be shared with MIT terms but what you add/change can be under GPL. Note that GPL is more restrictive than MIT.

To be honest, I really don't care as long as you don't try to impersonate me to spread malicious code ^^

**Comment by gusbemacbe** [comment]
> Hi, FYI you can speak english.

Yes, I can, but I wrote in French because you are French and your site is in French. I have studied French since 9 years old and today I know 15 languages.

Thank you for authorising. If I have some problems, can I call you to help me a bit? I hope it do not bother you.

**Comment by DarthWound** [comment]
No problem. Be aware that I'm working night shifts and this month I'm moving, so I'm quite busy currently and may not be able to answer quickly.
